# Generated by Django 4.0.4 on 2022-05-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=200)),
                ('is_done', models.BooleanField()),
            ],
        ),
    ]
